spring:
  profiles:
    active: dev
    
increment:
  client-username: ${CLIENT_USERNAME}
  client-password: ${CLIENT_PASSWORD}
  
  url:
    increment: api/increment
    
---
spring:
  profiles: dev
    
server:
    port: 8090
    
increment:
  client-username: demo
  client-password: demo 

---
spring:
  profiles: prod
   

    
    
    