spring:
  profiles:
    active: dev
    
increment:
  client-username: demo
  client-password: demo
  
  url:
    increment: api/increment
    proxy-php: "<location>/proxy?"
    
---
spring:
  profiles: dev
    
server:
    port: 8090
    
increment:
  client-username: demo
  client-password: demo 

---
spring:
  profiles: prod
   

    
    
    